### ISSUE TITLE
feedback route: list of index out of range

### ISSUE THREAD

**Issue by extreme4all** [Bot-detector/Bot-Detector-Core-Files#184]
```
Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File "/code/./api/routers/legacy.py", line 789, in receive_plugin_feedback
    voter_data = voter_data.rows2dict()[0]
IndexError: list index out of range
```

**Comment by Ferrariic** [comment]
What was the route you accessed when this bug occurred and what were your inputs/expected outputs?

**Comment by Ferrariic** [comment]
I attempted to reproduce this bug and was unable to. Could you give a bit more information to reproduce the bug?

**Comment by Ferrariic** [comment]
This bug triggers when a user uses Anonymous mode on the legacy route.

**Comment by extreme4all** [comment]
When a user posts feedback to one of the legacy routes, as an anonymous user.

if the user does not exist it tries to insert the user
```
async def sql_insert_player(player_name):
    sql_insert = "insert ignore into Players (name) values(:player_name);"

    param = {
        'player_name': player_name
    }

    await execute_sql(sql_insert, param=param)
    player = await sql_get_player(player_name)
    return player
```
it uses get player which seem to be changed
```
async def sql_get_player(player_name):
    """Attempts to get data for a player whose names matches player_name."""
    sql_player_id = 'select * from Players where normalized_name LIKE :normalized_name'

    param = {
        'normalized_name': await to_jagex_name(player_name)
    }

    # returns a list of players
    player = await execute_sql(sql_player_id, param=param)

    player = player.rows2dict()

    return None if len(player) == 0 else player[0]
```

**Comment by extreme4all** [comment]
phase out planned
