### ISSUE TITLE
Some names never make it to the database

### ISSUE THREAD

**Issue by Ferrariic** [Bot-detector/Bot-Detector-Core-Files#363]
For some reason, certain names never make it to the database. Example name 'Ferrariic' - this was tested on w330 HousePortals where there were ample numbers of active plugin users, during this test StgReports table was monitored for my RSN, and it did not appear.

This could indicate that we're missing player sightings in the database, which would prevent us from updating reportLatest, and inserting new players in the db, affecting predictions and the system in general.

**Comment by Ferrariic** [comment]
The following testing entry was performed on the current route:

```
[
  {
    "reporter": "extreme4all",
    "reported": "Ferrariic",
    "region_id": 12598,
    "x": 10,
    "y": 10,
    "z": 10,
    "ts": 1642241688,
    "on_members_world": 1,
    "on_pvp_world": 0,
    "world_number": 330,
    "equipment": {
      "HEAD": 0,
      "AMULET": 0,
      "TORSO": 0,
      "LEGS": 0,
      "BOOTS": 0,
      "CAPE": 0,
      "HANDS": 0,
      "WEAPON": 0,
      "SHIELD": 0
    },
    "equipment_ge": 0
  }
]
```

This error was given when printing the dataframe on lines 166 and 173 of the current deployment on dev.

```
2022-01-15 05:17:11,265 - api.routers.legacy_debug - DEBUG - Received: 1 from: ['extreme4all']
2022-01-15 05:17:11,269 - api.middleware - DEBUG - url='http://127.0.0.1:8000/1.3.7.2/plugin/detect/0';process_time=0.012966394424438477
INFO:     127.0.0.1:64034 - "POST /1.3.7.2/plugin/detect/0 HTTP/1.1" 200 OK
   confirmed_ban  confirmed_player          created_at hardcore_ironman  id ironman  label_id  label_jagex         name normalized_name  possible_ban ultimate_ironman          updated_at
0              0                 1 2021-03-14 20:22:45             None   1    None         1            0  extreme4all     extreme4all             0             None 2022-01-09 03:50:28
1              0                 1 2021-03-14 20:42:37             None   8    None         1            0    ferrariic       ferrariic             0             None 2022-01-09 04:35:38
Empty DataFrame
Columns: [reporter, reported, region_id, x, y, z, ts, on_members_world, on_pvp_world, world_number, equipment, equipment_ge, confirmed_ban, confirmed_player, created_at, hardcore_ironman, id, ironman, label_id, label_jagex, name, normalized_name, possible_ban, ultimate_ironman, updated_at]
Index: []
2022-01-15 05:17:12,392 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-17' coro=<detect() done, defined at C:\Users\thear\Documents\GitHub\Bot-Detector-Core-Files\.\api\routers\legacy_debug.py:117> exception=IndexError('Detection Submission Error: [] was not found in    confirmed_ban  confirmed_player          created_at hardcore_ironman  id ironman  label_id  label_jagex         name normalized_name  possible_ban ultimate_ironman          updated_at\n0              0                 1 2021-03-14 20:22:45 
            None   1    None         1            0  extreme4all     extreme4all             0             None 2022-01-09 03:50:28\n1              0                 1 2021-03-14 20:42:37             None   8    None         1
 0    ferrariic       ferrariic             0             None 2022-01-09 04:35:38.')>
Traceback (most recent call last):
  File "C:\Users\thear\Documents\GitHub\Bot-Detector-Core-Files\.\api\routers\legacy_debug.py", line 177, in detect
    df["reporter_id"] = df_names.query(f"normalized_name == {reporter}")['id'].to_list()[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\thear\Documents\GitHub\Bot-Detector-Core-Files\.\api\routers\legacy_debug.py", line 179, in detect
    raise IndexError(f"Detection Submission Error: {reporter} was not found in {df_names}.")
IndexError: Detection Submission Error: [] was not found in    confirmed_ban  confirmed_player          created_at hardcore_ironman  id ironman  label_id  label_jagex         name normalized_name  possible_ban ultimate_ironman          updated_at
0              0                 1 2021-03-14 20:22:45             None   1    None         1            0  extreme4all     extreme4all             0             None 2022-01-09 03:50:28
1              0                 1 2021-03-14 20:42:37             None   8    None         1            0    ferrariic       ferrariic             0             None 2022-01-09 04:35:38.
```

**Comment by Ferrariic** [comment]
This payloads yields a successful insert into the StgReports table, and represents my true RSN as capitalized properly. 
```
[
  {
    "reporter": "extreme4all",
    "reported": "Ferrariic",
    "region_id": 12598,
    "x": 10,
    "y": 10,
    "z": 10,
    "ts": 1642241688,
    "on_members_world": 1,
    "on_pvp_world": 0,
    "world_number": 330,
    "equipment": {
      "HEAD": 0,
      "AMULET": 0,
      "TORSO": 0,
      "LEGS": 0,
      "BOOTS": 0,
      "CAPE": 0,
      "HANDS": 0,
      "WEAPON": 0,
      "SHIELD": 0
    },
    "equipment_ge": 0
  }
]
```

There seems to be multiple issues with this legacy route, namely if the In-Game Plugin Retrieved name is incongruent with the name in the database - this may yield errors.

**Comment by Ferrariic** [comment]
Regarding this issue the following terminology will be used to explain the condition:

PRSN - Plugin Retrieved RSN (RSN Present in-game in terms of capitalization prior to normalization)
SQL-RSN - `Name` column RSN
nSQL-RSN - `normalized_name` column RSN

Current findings: 
It seems that if PRSN != SQL-RSN, the report will fail. When PRSN == SQL-RSN the StgReport goes through.

**Comment by Ferrariic** [comment]
According to this code block in the legacy-debug route for /reports/

```
    # 1.1) Normalize and validate all names
    clean_names = [await to_jagex_name(name) for name in names if await is_valid_rsn(name)]

    # 2) Get IDs for all unique names
    data = await sql_select_players(clean_names)

    # 3) Create entries for players that do not yet exist in Players table
    existing_names = [d["normalized_name"] for d in data]
    new_names = set([name for name in clean_names]).difference(existing_names)
    
    # 3.1) Get those players' IDs from step 3
    if new_names:
        param = [{"name": name, "nname":name} for name in new_names] # problematic situation
        await batch_function(sql_insert_player, param)
        data.extend(await sql_select_players(new_names))

```

This situation could be extended to new accounts that have not been previously detected by the plugin. This is because the route:

1. Cleans the PRSN
2. Inserts the new nSQL-RSN in the place of the SQL-RSN and nSQL-RSN
3. Due to the incongruency of PRSN != SQL-RSN due to nSQL-RSN taking its place, the name cannot be resolved and errors appear for insertion.

While we have no plans to currently work on the legacy route, this should be taken into account when resolving the future v1/report route, and a hot-fix should be performed for this legacy-debug route as well to resolve current issues.

**Comment by Ferrariic** [comment]
Further information for rectifying the condition will be given in #owner chat.

Suggested solution for a hot-fix:
1. All names should be globally normalized in the forefront of the API and checked against the normalized-name parameter instead of the name parameter.

This will allow us to treat every name as coming in as normalized, which will allow us to compare it to an already normalized column.

**Comment by Ferrariic** [comment]
Reopening this issue - will have to reimplement these changes on the new branch.
